apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jhpark-kr/k8s-manifests.git' # 본인 Git 주소
    targetRevision: HEAD
    path: root-apps # ◀ 중요: 개별 앱 선언서들이 모여있는 폴더를 통째로 바라봅니다.
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
