apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - karpenter-nodepool.yaml
namePrefix: prd-
commonLabels:
  environment: production
patches:
  - target:
      kind: Deployment
      name: spring-boot-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 10 # 운영 환경은 대규모 인프라 대비 10대 구동 설정